---
# GitHub Actions configuration file
name: Grails Tests
permissions: read-all

on: # yamllint disable-line rule:truthy
  # Trigger the tests at every push.
  push:
    branches-ignore: [upload]
  pull_request:
    branches: [master, main]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Check Gradle version
        run: ./gradlew --version

      - name: Run Integration Tests
        run: ./gradlew integrationTest

      # Upload test result artifacts
      - name: Archive test result artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: |
            build/test-results
